# SPDX-License-Identifier: Apache-2.0

use Mojo::Base -strict;
use autotest;
use testapi;

# This distribution deliberately has no visual needles. The test is a direct
# os-autoinst/QEMU boot gate whose evidence is the kernel and systemd serial
# stream generated by the actual composed disk.
autotest::loadtest 'tests/boot.pm';

1;
