# Managed by Doors DNS selector: unbound-cloudflare
server:
    interface: 127.0.0.1
    interface: ::1
    port: 5335
    access-control: 127.0.0.0/8 allow
    access-control: ::1 allow
    do-daemonize: no
    username: "unbound"
    directory: "/etc/unbound"
    auto-trust-anchor-file: "/var/lib/unbound/root.key"
    module-config: "validator iterator"
    val-permissive-mode: no
    harden-dnssec-stripped: yes
    qname-minimisation: yes
    aggressive-nsec: yes
    prefetch: yes
    hide-identity: yes
    hide-version: yes
    tls-cert-bundle: "/etc/pki/tls/certs/ca-bundle.crt"
forward-zone:
    name: "."
    forward-tls-upstream: yes
    forward-addr: 1.1.1.1@853#cloudflare-dns.com
    forward-addr: 1.0.0.1@853#cloudflare-dns.com
